apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: hello-ml
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ml
spec:
  selector:
    matchLabels:
      app: hello-ml
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-ml
    spec:
      containers:
        - name: flask-ml
          image: demo_image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000